[build]
  publish = "build"  # The directory to publish (for React, it's usually 'build')
  functions = "functions"  # The directory for Netlify Functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
