const express = require("express");
const router = express.Router();

const siteNameLocations = [
  { siteId: 1, siteName: "アサヒビール" },
  { siteId: 2, siteName: "アドヴィックス刈谷" },
  { siteId: 3, siteName: "伊丹産業" },
  { siteId: 4, siteName: "イビデン大垣中央" },
  { siteId: 5, siteName: "イビデン河間" },
  { siteId: 6, siteName: "SLNG" },
  { siteId: 7, siteName: "王子マテリア江戸川" },
  { siteId: 8, siteName: "沖電牧港" },
  { siteId: 9, siteName: "義芳化学" },
  { siteId: 10, siteName: "クラレ" },
  { siteId: 11, siteName: "KYB岐阜北" },
  { siteId: 12, siteName: "神戸PC 3号機" },
  { siteId: 13, siteName: "神戸PC 4号機" },
  { siteId: 14, siteName: "Ｓｉａｍ DENSO" },
  { siteId: 15, siteName: "CCM" },
  { siteId: 16, siteName: "椎の森パワー" },
  { siteId: 17, siteName: "JFEスチール" },
  { siteId: 18, siteName: "ジェイテクト岡崎" },
  { siteId: 19, siteName: "JES" },
  { siteId: 20, siteName: "静岡ガス&パワー" },
  { siteId: 21, siteName: "昭和産業" },
  { siteId: 22, siteName: "新宿地冷" },
  { siteId: 23, siteName: "SUBARU" },
  { siteId: 24, siteName: "SUBARU大泉" },
  { siteId: 25, siteName: "DNP鶴瀬" },
  { siteId: 26, siteName: "太平洋セメント" },
  { siteId: 27, siteName: "太平洋セメント埼玉" },
  { siteId: 28, siteName: "中外製薬藤枝" },
  { siteId: 29, siteName: "中部国際空港" },
  { siteId: 30, siteName: "TPA 1号機（KG12V）" },
  { siteId: 31, siteName: "TPA 2号機（KG18V）" },
  { siteId: 32, siteName: "TMMIN" },
  { siteId: 33, siteName: "デイ・シイ川崎" },
  { siteId: 34, siteName: "帝人三島" },
  { siteId: 35, siteName: "テクノ上越" },
  { siteId: 36, siteName: "テクノ袖ヶ浦" },
  { siteId: 37, siteName: "デンソー岩手" },
  { siteId: 38, siteName: "デンソー幸田" },
  { siteId: 39, siteName: "デンソー善明" },
  { siteId: 40, siteName: "デンソー大安" },
  { siteId: 41, siteName: "デンソー第一安城" },
  { siteId: 42, siteName: "デンソー第二安城" },
  { siteId: 43, siteName: "デンソー高棚" },
  { siteId: 44, siteName: "デンソー豊橋" },
  { siteId: 45, siteName: "デンソー西尾北" },
  { siteId: 46, siteName: "デンソー西尾南" },
  { siteId: 47, siteName: "東京ガス根岸" },
  { siteId: 48, siteName: "東京都下水道局" },
  { siteId: 49, siteName: "東芝横浜" },
  { siteId: 50, siteName: "東洋紡敦賀" },
  { siteId: 51, siteName: "東レ三島" },
  { siteId: 52, siteName: "特種東海製紙三島" },
  { siteId: 53, siteName: "豊科フィルム" },
  { siteId: 54, siteName: "トヨタ車体" },
  { siteId: 55, siteName: "トヨタ東日本" },
  { siteId: 56, siteName: "トヨタ北海道" },
  { siteId: 57, siteName: "トヨタ三好" },
  { siteId: 58, siteName: "トヨタ元町" },
  { siteId: 59, siteName: "虎ノ門・麻布台" },
  { siteId: 60, siteName: "那珂GP" },
  { siteId: 61, siteName: "長岡パワー" },
  { siteId: 62, siteName: "日軽金清水" },
  { siteId: 63, siteName: "日産追浜" },
  { siteId: 64, siteName: "日東紡績" },
  { siteId: 65, siteName: "日本キャンパック" },
  { siteId: 66, siteName: "日本橋室町" },
  { siteId: 67, siteName: "Berkprai" },
  { siteId: 68, siteName: "HATC" },
  { siteId: 69, siteName: "パナソニック大泉増設" },
  { siteId: 70, siteName: "パナソニック東京" },
  { siteId: 71, siteName: "日野羽村" },
  { siteId: 72, siteName: "富士電機松本" },
  { siteId: 73, siteName: "北海道ガス石狩" },
  { siteId: 74, siteName: "北海道ガス札幌" },
  { siteId: 75, siteName: "本田鈴鹿" },
  { siteId: 76, siteName: "マルヤス工業" },
  { siteId: 77, siteName: "Malay Sino" },
  { siteId: 78, siteName: "茂原パワー" },
  { siteId: 79, siteName: "森永乳業" },
  { siteId: 80, siteName: "八重洲" },
  { siteId: 81, siteName: "トヨタ本社" },
  { siteId: 82, siteName: "Ratch" },
  { siteId: 83, siteName: "レンゴー利根川" },
  { siteId: 84, siteName: "RenKorat" },
];

router.get("/location-site-names", (req, res) => {
  res.json(siteNameLocations);
});

module.exports = router;
